language: node_js
node_js:
  - "4"
  - "6"
  - "node"
env:
  - FORMDATA_VERSION=1.0.0
  - FORMDATA_VERSION=1.0.0 ENCODING=yes
  - FORMDATA_VERSION=2.1.0
  - FORMDATA_VERSION=2.1.0 ENCODING=yes
before_script:
  - 'if [ "$FORMDATA_VERSION" ]; then npm install form-data@^$FORMDATA_VERSION; fi'
  - 'if [ "$ENCODING" = "yes" ]; then npm install encoding; fi'
before_install: npm install -g npm
script: npm run coverage
cache:
  directories:
    - node_modules
